### ISSUE TITLE
Extra spaces between elements in option line results in exception

### ISSUE THREAD

**Issue by mdwhitten** [mdwhitten/microwave-networks#21]
The standard indicates:

> Option line parameters are separated by one or more whitespace

However, currently more than one space results in an exception being thrown.

**Comment by mdwhitten** [comment]
FYI @mkrmasch. Let's find more of these and get a new version pushed.

**Comment by mkrmasch** [comment]
I had a closer look in our use cases and also checked that the code e.g.  already handles multiple white spaces in the network parameters section correctly. So I did not find more issues or needs for changes. Thank you.
